version: "3.8"
services:
  lean-ovation-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.local
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/lean-ovation
  mongodb:
    image: mongo:7.0
    ports:
      - 27017:27017
