import {
  Container,
  CssBaseline,
  ThemeProvider,
  createTheme,
} from "@mui/material";
import type { Metadata } from "next";
import theme from "./theme";
import Auth from "./Auth";
import Navbar from "./Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <CssBaseline />
      <body>
        <Auth>
          <ThemeProvider theme={theme}>
            <Navbar />
            <Container sx={{ py: 8 }}>{children}</Container>
          </ThemeProvider>
        </Auth>
      </body>
    </html>
  );
}
